config/routes.rb
Rails.application.routes.draw do

  resources :parts do
    collection do
      get 'search'
    end
  end

  resources :cars do
    collection do
      get 'search'
    end
  end

  resources :makes do
    collection do
      get 'search'
    end
  end

  resources :parts
  resources :cars
  resources :makes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  # Sets up the many-to-many
  belongs_to :make
  has_many :car_parts
  has_many :parts, through: :car_parts

  validates :car_model, presence: true
  validates :vin_number, presence: true
end

app/models/car_part.rb
class CarPart < ApplicationRecord
  belongs_to :car
  belongs_to :part
end

app/models/make.rb
class Make < ApplicationRecord
  has_many :cars

  validates :name, presence: true, length: { minimum: 4 }
  validates :country, presence: true
end

app/models/part.rb
class Part < ApplicationRecord
  # many-to-many through a join model.
  has_many :car_parts, dependent: :delete_all
  has_many :cars, through: :car_parts

  validates :part_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @makes = Make.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @makes = Make.all
  end

  # GET /cars/new.
  def new
    @car = Car.new
    @parts = Part.all
    @makes = Make.all
  end

  # GET /cars/1/edit
  def edit
    @parts = Part.all
    @makes = Make.all
  end

  def search
    @cars = Car.where("car_model like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @makes = Make.all

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def car_params
    params.require(:car).permit(:car_make, :car_model, :vin_number, :make_id, :part_ids => [])
  end
end

app/controllers/makes_controller.rb
class MakesController < ApplicationController
  before_action :set_make, only: [:show, :edit, :update, :destroy]

  # GET /makes
  # GET /makes.json
  def index
    @makes = Make.all
  end

  # GET /makes/1
  # GET /makes/1.json
  def show
  end

  # GET /makes/new
  def new
    @make = Make.new
  end

  # GET /makes/1/edit
  def edit
  end

  def search
    @makes = Make.where("name like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /makes
  # POST /makes.json
  def create
    @make = Make.new(make_params)

    respond_to do |format|
      if @make.save
        format.html { redirect_to @make, notice: 'Make was successfully created.' }
        format.json { render :show, status: :created, location: @make }
      else
        format.html { render :new }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /makes/1
  # PATCH/PUT /makes/1.json
  def update
    respond_to do |format|
      if @make.update(make_params)
        format.html { redirect_to @make, notice: 'Make was successfully updated.' }
        format.json { render :show, status: :ok, location: @make }
      else
        format.html { render :edit }
        format.json { render json: @make.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makes/1
  # DELETE /makes/1.json
  def destroy
    @make.destroy
    respond_to do |format|
      format.html { redirect_to makes_url, notice: 'Make was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_make
    @make = Make.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def make_params
    params.require(:make).permit(:name, :country)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
    @cars = Car.all
  end

  # GET /parts/1/edit
  def edit
    @cars = Car.all
  end

  def search
    @parts = Part.where("part_name like ?", "%#{params[:query]}%")
    render :index
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_part
    @part = Part.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def part_params
    params.require(:part).permit(:part_name, :car_ids => [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :make_id %>
    <%= form.collection_select :make_id, Make.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :car_model %>
    <%= form.text_field :car_model %>
  </div>

  <div class="field">
    <%= form.label :vin_number %>
    <%= form.text_field :vin_number %>
  </div>

  <div class="field">
    <%= form.label :part_id %>
    <%= form.collection_select(:part_id, Part.all, :id, :part_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Vin</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
    <tr>
      <td><%= car.make.name %></td>
      <td><%= car.car_model %></td>
      <td><%= car.vin_number %></td>
      <td><%= link_to 'Show', car %></td>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <%= form_tag(search_cars_url, method: "get") do %>
    <%= label_tag(:query, "Search for Model:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Model Search") %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car make:</strong>
  <%= @car.make.name %>
</p>

<p>
  <strong>Car model:</strong>
  <%= @car.car_model %>
</p>

<p>
  <strong>Vin number:</strong>
  <%= @car.vin_number %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/makes/_form.html.erb
<%= form_with(model: make, local: true) do |form| %>
  <% if make.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(make.errors.count, "error") %> prohibited this make from being saved:</h2>

      <ul>
        <% make.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/makes/edit.html.erb
<h1>Editing Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Show', @make %> |
<%= link_to 'Back', makes_path %>

app/views/makes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Make</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @makes.each do |make| %>
    <tr>
      <td><%= make.name %></td>
      <td><%= make.country %></td>
      <td><%= link_to 'Show', make %></td>
      <td><%= link_to 'Edit', edit_make_path(make) %></td>
      <td><%= link_to 'Destroy', make, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  <%= form_tag(search_makes_url, method: "get") do %>
    <%= label_tag(:query, "Search for Make:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Makes Search") %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Make', new_make_path %>

app/views/makes/new.html.erb
<h1>New Make</h1>

<%= render 'form', make: @make %>

<%= link_to 'Back', makes_path %>

app/views/makes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @make.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @make.country %>
</p>

<%= link_to 'Edit', edit_make_path(@make) %> |
<%= link_to 'Back', makes_path %>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part_name %>
    <%= form.text_field :part_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
  <tr>
    <th>Part name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @parts.each do |part| %>
    <tr>
      <td><%= part.part_name %></td>
      <td><%= link_to 'Show', part %></td>
      <td><%= link_to 'Edit', edit_part_path(part) %></td>
      <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>

  <%= form_tag(search_parts_url, method: "get") do %>
    <%= label_tag(:query, "Search for Part:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Parts Search") %>
  <% end %>

</table>

<br>

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part name:</strong>
  <%= @part.part_name %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>